# Generated by Django 6.0.6 on 2026-06-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='mensaje',
            new_name='comentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='username',
            field=models.CharField(default='Anónimo', max_length=100),
            preserve_default=False,
        ),
    ]
