# Generated by Django 6.0.6 on 2026-06-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_contactnow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ContactNow',
        ),
    ]
